CREATE TABLE IF NOT EXISTS `M_USER` (
  `id` VARCHAR(8) NOT NULL PRIMARY KEY,
  `user_name` VARCHAR(256) NOT NULL DEFAULT '',
  `mail_address` VARCHAR(256) NOT NULL DEFAULT '',
  `auth_key` VARCHAR(256) NOT NULL DEFAULT ''
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;